### ISSUE TITLE
v0.30 crashes under ams

### ISSUE THREAD

**Issue by muxi1** [Chrscool8/Homebrew-Details#1]
Hi @Chrscool8 

v0.30 crashes under ams 0.13.0 / emuMMC 10.0.4. v0.20 runs without problems.

Tested via HB menu in applet mode & high memory mode

**Comment by Chrscool8** [comment]
Thanks so much for the report! Strangely, I'm on those exact conditions and I'm all clear.

Does it crash immediately or after a few seconds? 

Hard Atmosphere crash (reboot) or just app crash? 

Would you say that you have a large number of nros or folders with subfolders in the /switch/ directory?

**Comment by muxi1** [comment]
> Does it crash immediately or after a few seconds?
If the tool is executed in applet mode, a fatal ams crash occurs immediately

> Hard Atmosphere crash (reboot) or just app crash?
App Crash only, if it is started via a forwarder (I use a forwarder for the hbmenu)

> Would you say that you have a large number of nros or folders with subfolders in the /switch/ directory?
I currently use 13 HB-Tools in the switch folder

**Comment by Chrscool8** [comment]
Excellent, this helps me narrow it down a lot. Thanks! I'm on it!

**Comment by Chrscool8** [comment]
Out of curiosity, do you have any apps downloaded from the HB App Store? I think I have an idea.

**Comment by muxi1** [comment]
> do you have any apps downloaded from the HB App Store?

No, I do this manually because the tools are often not up to date. Shall I test this for you and download an app from the store?

**Comment by Chrscool8** [comment]
I think that's all I needed to know. I have a strooong feeling that it's expecting >0 apps in the new update. If you have a couple minutes, I'd love to hear if downloading any single app (not theme) from the App Store fixes your crash.

**Comment by muxi1** [comment]
Yeah, that's what caused the crash! There are no homebrews that have been downloaded from the App Store! I have now downloaded a tool from the App Store and now everything works!

**Comment by Chrscool8** [comment]
Hell yeah. Thank you so much for working with me on this. I found one missing 'folder exists' check and your experiment confirms that that was almost certainly it! 

If you want to remove app store stuff, you should be able to just remove /switch/appstore/ and be back to your previous state.

v0.31 is incoming with the fix for 0 app store apps.

Thanks again!
