### ISSUE TITLE
v0.42 causes a system crash

### ISSUE THREAD

**Issue by muxi1** [Chrscool8/Homebrew-Details#2]
After running v0.42 and scanning the apps, a fatal crash occurs, even if an App Store title is present in the setting.

**Comment by Chrscool8** [comment]
Darn it, but thank you again!

I have to sleep now, but I have a thought. Is your switch internet enabled? By 90dns or otherwise?

**Comment by muxi1** [comment]
> Is your switch internet enabled? By 90dns or otherwise?

Yes it is.

**Comment by Chrscool8** [comment]
Okay, I was hoping it wasn’t, haha. I never tested in airplane mode. Right, guess that adds up that you tried AppStore apps... I’m behind on sleep. 

Yeah, in that case, I’m not sure off the top of my head. I’ll run a battery in the morning and maybe make a couple debuggy versions to narrow it down. 

Thanks!

**Comment by muxi1** [comment]
> I never tested in airplane mode.

Not that there's any misunderstanding here. I am NOT using my console in Airplane mode, but have a permanent internet connection under an emuMMC in Inconito mode & 90DNS.

**Comment by Chrscool8** [comment]
It does help! I'm fairly sure it's in the update checker, maybe if it doesn't initialize correctly, because I can repro a crash in airplane at the same point (though I know you're not).

**Comment by Chrscool8** [comment]
[homebrew_details_v0.43.nro.zip](https://github.com/Chrscool8/Homebrew-Details/files/4914692/homebrew_details_v0.43.nro.zip)

This may be the easy solution! I accidentally left a panic on error in there... oops. It's another issue that you aren't successfully connecting to the github, but at least it will gracefully handle it now. Lemme know how that works for you!

**Comment by muxi1** [comment]
The problem was fixed in this version!

**Comment by Chrscool8** [comment]
Awesome! Now I'm just curious if your Switch will see the next version from that version. Please let me know if it does! Thanks!
