### ISSUE TITLE
Problems When Creating My Own Forwarder

### ISSUE THREAD

**Issue by Aliasim800** [Chrscool8/Homebrew-Details#3]
## **Describe the bug**
A clear and concise description of what the bug is:
When Creating My Own Forwarder Using The Tool NRO2NSP To launch The App, A few Weird things happen that I think can be fixed easily.

## **To Reproduce**

1.Create A Homebrew Details Forwarder Using The tool NRO2NSP (via sdmc and I forward it using the directory /switch/.nro forwarders/homebrew details.nro

2.Install the forwarder

3.Launch the forwarder and I see a few bugs that need to be fixed. (And there may be more bugs that happen that I don't know about)

## **Expected behavior**
To see the forwarder launch like a the normal homebrew app.

## **Screenshots**
Yep I Took some screenshots to show what bugs I'm talking about:
![iwkz](https://user-images.githubusercontent.com/64366457/88481201-fc467d00-cf51-11ea-93ec-7d473e101344.jpg)
![iwko](https://user-images.githubusercontent.com/64366457/88481239-2435e080-cf52-11ea-9f0c-3f78ecf2cf7a.jpg)
![iwkX](https://user-images.githubusercontent.com/64366457/88481266-3879dd80-cf52-11ea-85d9-91c855b47077.jpg)

## **System Type and Version:**
 - App Version 0.74 Stealth Launch
 - EmuNAND
 - OS Version 10.0.4
 - CFW Version Atmosphere v0.13.0
 - Launching from channel or applet:
Launching as a forwarder

## **Additional context**
I know that there is already a forwarder included in the releases but I want to actually literally "forward" the app from the switch directory to the .nro. So I would really appreciate it if this gets fixed.

Thank You!

**Comment by Chrscool8** [comment]
Thanks for the report! That's a romfs problem. I used nro2nsp to make my forwarder, too, so I wonder what the difference is. First suspicions are that maybe the periods or the spaces in the forwarded path are messing it up. Are you on the latest (beta) nro2nsp? Can you try creating a forwarder exactly like the one I made to see if it works correctly? (sdmc:/switch/homebrew_details.nro)

**Comment by Aliasim800** [comment]
Yes I'm on the latest beta release of nro2nsp,
I'll create a forwarder with the directory you say so.
Thanks for replying!

**Comment by Chrscool8** [comment]
This may be fixed after running v0.85 once from hbmenu and then trying again whatever way you had it set up before. :)

**Comment by Aliasim800** [comment]
Thank you. I just remade a new forwarder the way you said it and it works for some reason. Don't know why.
Hope this gets fixed though in the future.
Thanks and keep up the great work!

**Comment by Aliasim800** [comment]
Oh and I also have a suspicion is that I'm forwarding the homebrew via (sdmc:/switch/.nro forwarders/homebrew_details.nro) it may be because I'm  directing the forwarder to launch a .nro from a hidden folder because I've put a dot before the name of the folder it makes it a hidden folder. So the issue may be that.

**Comment by Aliasim800** [comment]
Yes the problem is that if you forward with a path witch had a hidden folder in it, it causes issues. Would be cool if it can get fixed but I don't mind it.
