### ISSUE TITLE
Deleting App doesn't delete its folder

### ISSUE THREAD

**Issue by BennyAlex** [Chrscool8/Homebrew-Details#4]
**Describe the bug**
When I delete some apps, the original folder is still present on the SD card and thus visible in the hbmenu.

**To Reproduce**
Manage -> delete app -> empty folder still visible in hbmenu

**Expected behavior**
Also deletes the folder, not only the nro

**Screenshots**

**System Type and Version:**
 - App Version [latest]
 - EmuNAND
 - OS Version [e.g. 10.2.0]
 - CFW Version [e.g. Atmosphere v0.15.0]
 - Launching from channel

**Additional context**

**Comment by Chrscool8** [comment]
Makes sense to me, I'll add that to the list! Thanks!

**Comment by Chrscool8** [comment]
Done! Will appear in the next released version.
